baseURL = "https://mryoung2022.github.io/"
languageCode = "zh-cn"
title = "Susan's Blog"
theme = "hugo-theme-tokiwa"
hasCJKLanguage = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

copyright = "© 2025 Susan"

[author]
  name = "Susan"
  email = "you@example.com"

[params.author]
  name = "Susan"
  email = "you@example.com"

[markup]
  [markup.highlight]
    style = "monokailight"
    lineNos = true
    codeFences = true

  [markup.goldmark.renderer]
    unsafe = true

[pagination]
  pagerSize = 10

[params]
  description = "Susan 的个人博客"
  env = "production"

  defaultDark = false
  enableDarkModeToggle = true

  fuse = true
  math = true
  useChineseFonts = true

  favicon = "img/favicon-32x32.png"
  bannerFont = "fonts/exampleFont"

  postDateFormat = "2006-01-02"

  showAds = false

[menu]

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 1

[[menu.main]]
  name = "数学"
  url = "/categories/数学/"
  parent = "分类"
  weight = 2

[[menu.main]]
  name = "物理"
  url = "/categories/物理/"
  parent = "分类"
  weight = 3

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params.social]
  bilibili = "https://space.bilibili.com/1317044017"
  github = "https://github.com/mryoung2022"

[outputs]
  home = ["HTML", "RSS", "JSON"]